updated help text

diff --git a/makeimg b/makeimg
--- a/makeimg
+++ b/makeimg
@@ -131,12 +131,12 @@ confirm() {
 mkdir -p $output_dir
 
 if [ ! $optimized ] && ! which mozjpeg &>/dev/null; then
-  echo 'ERROR: mozjpeg required, but not found' >&2
+  echo 'ERROR: mozjpeg (https://www.npmjs.com/package/mozjpeg) required, but not found' >&2
   exit 4
 fi
 
 if ! which identify &>/dev/null; then
-  echo 'ERROR: imagemagick must be installed' >&2
+  echo 'ERROR: imagemagick required for identify(1) and convert(1), but commands were not found' >&2
   exit 5
 fi
 
